version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: moneymaster
      POSTGRES_PASSWORD: moneymaster123
      POSTGRES_DB: moneymaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  redis_data:
  postgres_data: 